INITIAL_AREAS = [
    {"id": "hallway", "name_ru": "Прихожая"},
    {"id": "living", "name_ru": "Гостиная"},
    {"id": "kitchen", "name_ru": "Кухня"},
    {"id": "bedroom", "name_ru": "Спальня"},
    {"id": "bathroom", "name_ru": "Ванная"},
    {"id": "outdoor", "name_ru": "Улица"},
    {"id": "utility", "name_ru": "Котельная"},
]

ROOM_RU_BY_ID = {area["id"]: area["name_ru"] for area in INITIAL_AREAS}

INITIAL_ENTITIES = [
    {
        "entity_id": "binary_sensor.motion_hallway",
        "name": "Xiaomi Mi Motion Sensor 2",
        "model": "RTCGQ02LM",
        "domain": "binary_sensor",
        "room": "hallway",
        "room_ru": "Прихожая",
        "state": "off",
        "attributes": {"device_class": "motion"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-mi-motion-sensor-2",
        "power_kw": 0.0,
    },
    {
        "entity_id": "binary_sensor.door_hallway",
        "name": "Aqara Door and Window Sensor",
        "model": "MCCGQ11LM",
        "domain": "binary_sensor",
        "room": "hallway",
        "room_ru": "Прихожая",
        "state": "off",
        "attributes": {"device_class": "door"},
        "doc_url": "https://www.aqara.com/us/door_and_window_sensor.html",
        "power_kw": 0.0,
    },
    {
        "entity_id": "switch.plug_light_hallway",
        "name": "Xiaomi Mi Smart Plug 2",
        "model": "ZNCZ04LM",
        "domain": "switch",
        "room": "hallway",
        "room_ru": "Прихожая",
        "state": "off",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-smart-plug2",
        "power_kw": 0.04,
    },
    {
        "entity_id": "binary_sensor.motion_living",
        "name": "Xiaomi Mi Motion Sensor 2",
        "model": "RTCGQ02LM",
        "domain": "binary_sensor",
        "room": "living",
        "room_ru": "Гостиная",
        "state": "off",
        "attributes": {"device_class": "motion"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-mi-motion-sensor-2",
        "power_kw": 0.0,
    },
    {
        "entity_id": "light.ceiling_living",
        "name": "Yeelight Smart LED Bulb 1S",
        "model": "YLDP15YL",
        "domain": "light",
        "room": "living",
        "room_ru": "Гостиная",
        "state": "off",
        "attributes": {"color_mode": "color_temp"},
        "doc_url": "https://www.yeelight.com/en_US/product/lemon-color",
        "power_kw": 0.008,
    },
    {
        "entity_id": "switch.plug_tv_living",
        "name": "Xiaomi Mi Smart Plug 2",
        "model": "ZNCZ04LM",
        "domain": "switch",
        "room": "living",
        "room_ru": "Гостиная",
        "state": "off",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-smart-plug2",
        "power_kw": 0.15,
    },
    {
        "entity_id": "sensor.light_level_living",
        "name": "Xiaomi Mi Light Detection Sensor",
        "model": "GZCGQ01LM",
        "domain": "sensor",
        "room": "living",
        "room_ru": "Гостиная",
        "state": "0.0",
        "attributes": {"device_class": "illuminance", "unit_of_measurement": "lx"},
        "doc_url": "https://www.mi.com/global/",
        "power_kw": 0.0,
    },
    {
        "entity_id": "sensor.temperature_kitchen",
        "name": "Aqara Temperature and Humidity Sensor",
        "model": "WSDCGQ11LM",
        "domain": "sensor",
        "room": "kitchen",
        "room_ru": "Кухня",
        "state": "21.0",
        "attributes": {"device_class": "temperature", "unit_of_measurement": "°C"},
        "doc_url": "https://www.aqara.com/us/temperature_humidity_sensor.html",
        "power_kw": 0.0,
    },
    {
        "entity_id": "sensor.humidity_kitchen",
        "name": "Aqara Temperature and Humidity Sensor",
        "model": "WSDCGQ11LM",
        "domain": "sensor",
        "room": "kitchen",
        "room_ru": "Кухня",
        "state": "50.0",
        "attributes": {"device_class": "humidity", "unit_of_measurement": "%"},
        "doc_url": "https://www.aqara.com/us/temperature_humidity_sensor.html",
        "power_kw": 0.0,
    },
    {
        "entity_id": "switch.plug_kettle_kitchen",
        "name": "Xiaomi Mi Smart Plug 2",
        "model": "ZNCZ04LM",
        "domain": "switch",
        "room": "kitchen",
        "room_ru": "Кухня",
        "state": "off",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-smart-plug2",
        "power_kw": 2.2,
    },
    {
        "entity_id": "switch.plug_fridge_kitchen",
        "name": "Xiaomi Mi Smart Plug 2",
        "model": "ZNCZ04LM",
        "domain": "switch",
        "room": "kitchen",
        "room_ru": "Кухня",
        "state": "on",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-smart-plug2",
        "power_kw": 0.15,
    },
    {
        "entity_id": "binary_sensor.smoke_kitchen",
        "name": "Xiaomi Mi Smart Smoke Alarm",
        "model": "JTYJ-GD-01LM/BW",
        "domain": "binary_sensor",
        "room": "kitchen",
        "room_ru": "Кухня",
        "state": "off",
        "attributes": {"device_class": "smoke"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-mi-smoke-alarm",
        "power_kw": 0.0,
    },
    {
        "entity_id": "binary_sensor.motion_bedroom",
        "name": "Xiaomi Mi Motion Sensor 2",
        "model": "RTCGQ02LM",
        "domain": "binary_sensor",
        "room": "bedroom",
        "room_ru": "Спальня",
        "state": "off",
        "attributes": {"device_class": "motion"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-mi-motion-sensor-2",
        "power_kw": 0.0,
    },
    {
        "entity_id": "light.bedside_bedroom",
        "name": "Yeelight LED Bedside Lamp D2",
        "model": "YLCT01YL",
        "domain": "light",
        "room": "bedroom",
        "room_ru": "Спальня",
        "state": "off",
        "attributes": {"color_mode": "color_temp"},
        "doc_url": "https://www.yeelight.com/en_US/product/lemon-color",
        "power_kw": 0.02,
    },
    {
        "entity_id": "switch.plug_purifier_bedroom",
        "name": "Xiaomi Mi Air Purifier 3H",
        "model": "AC-M6-SC",
        "domain": "switch",
        "room": "bedroom",
        "room_ru": "Спальня",
        "state": "off",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-mi-air-purifier-3h",
        "power_kw": 0.038,
    },
    {
        "entity_id": "sensor.humidity_bathroom",
        "name": "Aqara Temperature and Humidity Sensor",
        "model": "WSDCGQ11LM",
        "domain": "sensor",
        "room": "bathroom",
        "room_ru": "Ванная",
        "state": "60.0",
        "attributes": {"device_class": "humidity", "unit_of_measurement": "%"},
        "doc_url": "https://www.aqara.com/us/temperature_humidity_sensor.html",
        "power_kw": 0.0,
    },
    {
        "entity_id": "switch.plug_boiler_bathroom",
        "name": "Xiaomi Mi Smart Plug 2",
        "model": "ZNCZ04LM",
        "domain": "switch",
        "room": "bathroom",
        "room_ru": "Ванная",
        "state": "off",
        "attributes": {"device_class": "plug"},
        "doc_url": "https://www.mi.com/global/product/xiaomi-smart-plug2",
        "power_kw": 2.0,
    },
    {
        "entity_id": "binary_sensor.motion_outdoor",
        "name": "Aqara Motion Sensor P1",
        "model": "MS-S02",
        "domain": "binary_sensor",
        "room": "outdoor",
        "room_ru": "Улица",
        "state": "off",
        "attributes": {"device_class": "motion"},
        "doc_url": "https://www.aqara.com/us/motion-sensor-p1.html",
        "power_kw": 0.0,
    },
    {
        "entity_id": "light.outdoor_light",
        "name": "Xiaomi Mi Smart Outdoor Light",
        "model": "MUE4115GL",
        "domain": "light",
        "room": "outdoor",
        "room_ru": "Улица",
        "state": "off",
        "attributes": {},
        "doc_url": "https://www.mi.com/global/",
        "power_kw": 0.015,
    },
    {
        "entity_id": "climate.thermostat_main",
        "name": "Xiaomi Smart Home Hub 2",
        "model": "ZNDMWG03LM",
        "domain": "climate",
        "room": "utility",
        "room_ru": "Котельная",
        "state": "20.0",
        "attributes": {
            "device_class": "temperature",
            "unit_of_measurement": "°C",
            "min": 17,
            "max": 25,
        },
        "doc_url": "https://www.mi.com/global/",
        "power_kw": 2.0,
    },
    {
        "entity_id": "sensor.solar_panel",
        "name": "Xiaomi Solar Panel",
        "model": "BHR5164GL",
        "domain": "sensor",
        "room": "outdoor",
        "room_ru": "Улица",
        "state": "0.0",
        "attributes": {"device_class": "power", "unit_of_measurement": "kW"},
        "doc_url": "https://www.mi.com/global/",
        "power_kw": 0.0,
    },
    {
        "entity_id": "sensor.battery_soc",
        "name": "Xiaomi Smart Battery Pack",
        "model": "BHR5164GL",
        "domain": "sensor",
        "room": "utility",
        "room_ru": "Котельная",
        "state": "50.0",
        "attributes": {"device_class": "battery", "unit_of_measurement": "%"},
        "doc_url": "https://www.mi.com/global/",
        "power_kw": 0.0,
    },
]
